services:
  api:
    container_name: todo-api
    build: 
      context: './api'
    volumes:
      - './api:/app'
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db/todo-db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-network
  
  db:
    container_name: todo-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-db
    volumes: 
      - ./db/db-data:/var/lib/mysql
    networks:
      - todo-network
    healthcheck:
      test: "exit 0"
  
networks:
  todo-network:
    name: todo-network