"""Update User Foreign Key in Todo

Revision ID: 0c0a3b2aaeae
Revises: 88f0efe032a9
Create Date: 2025-02-11 18:01:43.682421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0a3b2aaeae'
down_revision: Union[str, None] = '88f0efe032a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
