"""Update User table with a relationship

Revision ID: 9565d119b438
Revises: 0c0a3b2aaeae
Create Date: 2025-02-11 18:05:23.612166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9565d119b438'
down_revision: Union[str, None] = '0c0a3b2aaeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
